export const LOGIN_FAILURE = "LOGIN_FAILURE";
export const LOGIN_PENDING = "LOGIN_PENDING";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";

export const SIGN_UP_FAILURE = "SIGN_UP_FAILURE";
export const SIGN_UP_PENDING = "SIGN_UP_PENDING";
export const SIGN_UP_SUCCESS = "SIGN_UP_SUCCESS";

export const LOGOUT = "LOGOUT";

export const GET_PROBA_POINTS = "GET_PROBA_POINTS";
export const GET_PROBA_POINTS_FAILURE = "GET_PROBA_POINTS_FAILURE";
export const GET_PROBA_POINTS_SUCCESS = "GET_PROBA_POINTS_SUCCESS";
